### ISSUE TITLE
XRouting - Loses secondary Context, requires Clear Cache to start working again

### ISSUE THREAD

**Issue by JamesInWA** [SEDAdigital/XRouting#44] opened 2022-06-21 16:34 UTC
Hello,

I had enabled the xrouting.allow_debug_info in my System Settings.  When /gb/service.html Resource returned a HTTP 404, I added the &xrouting-debug=1 to the URL.  It shows the secondary Context was not loading.  

I ran Manage -> Clear Cache.  The /gb/service.html Resource was returned.  When I added the &xrouting-debug=1 to the URL, it shows both Contexts.

MarkH had suggested adding my Groups to the Context Access Permissions.  The Groups were added with 'Authority' = 9999, 'Access Policy' = Resource

https://community.modx.com/t/xrouting-contexts-secondary-context-errors-with-404/5188

Do you have any suggestions as to what I could try?

Thank you!

######################################################################################
######################################################################################

## MODX context map:

Array
(
    [_hosts] => Array
        (
            [apps.cipcontractors.com] => Array
                (
                    [0] => web
                )
        )

    [web] => Array
        (
            [assets_url] => /pe/assets/
            [base_url] => /pe/
            [error_page] => 1
            [http_host] => apps.cipcontractors.com
            [site_name] => Prairie Electric
            [site_start] => 1
            [site_url] => https://apps.cipcontractors.com/pe/
            [unauthorized_page] => 1
        )
)

## Matched context(s) (Array key defines match quality):

Array
(
)

######################################################################################
######################################################################################

## MODX context map:

Array
(
    [_hosts] => Array
        (
            [apps.cipcontractors.com] => Array
                (
                    [0] => web
                    [1] => gb
                )
        )

    [web] => Array
        (
            [assets_url] => /pe/assets/
            [base_url] => /pe/
            [error_page] => 1
            [http_host] => apps.cipcontractors.com
            [site_name] => Prairie Electric
            [site_start] => 1
            [site_url] => https://apps.cipcontractors.com/pe/
            [unauthorized_page] => 1
        )

    [gb] => Array
        (
            [assets_url] => /gb/assets/
            [base_url] => /gb/
            [error_page] => 157
            [http_host] => apps.cipcontractors.com
            [site_name] => GB Manchester
            [site_start] => 157
            [site_url] => https://apps.cipcontractors.com/gb/
            [unauthorized_page] => 157
        )

)

## Matched context(s) (Array key defines match quality):

Array
(
    [4] => gb
)

**Comment by christianseel** [comment] 2022-06-23 08:39
Closing this as its not a bug report, but most likely a config issue. Taking care of this at https://community.modx.com/t/xrouting-contexts-secondary-context-errors-with-404/5188/5

**Closed** 2022-06-23 08:40 UTC
